<?php

/**
 * BaseJazzeeConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property blob $value
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseJazzeeConfig extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('jazzee_config');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}