<?php

/**
 * BaseRecommendationPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $applicationPageID
 * @property integer $lorPageID
 * @property timestamp $deadline
 * @property string $recommenderEmail
 * @property ApplicationPage $ApplicationPage
 * @property Page $LORPage
 * @property Doctrine_Collection $Recommendation
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseRecommendationPage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('recommendation_page');
        $this->hasColumn('applicationPageID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('lorPageID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('deadline', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('recommenderEmail', 'string', 10000, array(
             'type' => 'string',
             'length' => '10000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ApplicationPage', array(
             'local' => 'applicationPageID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Page as LORPage', array(
             'local' => 'lorPageID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Recommendation', array(
             'local' => 'id',
             'foreign' => 'recommendationPageID'));
    }
}