<?php

/**
 * BasePageVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pageID
 * @property string $name
 * @property string $value
 * @property Page $Page
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BasePageVariable extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('page_variable');
        $this->hasColumn('pageID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));


        $this->index('page_variable', array(
             'fields' => 
             array(
              0 => 'pageID',
              1 => 'name',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'pageID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}