<?php

/**
 * BaseAuditLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $userID
 * @property string $log
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseAuditLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('audit_log');
        $this->hasColumn('userID', 'integer', 64, array(
             'type' => 'integer',
             'notnull' => true,
             'readonly' => true,
             'length' => '64',
             ));
        $this->hasColumn('log', 'string', 3000, array(
             'type' => 'string',
             'notnull' => true,
             'readonly' => true,
             'length' => '3000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}