<?php

/**
 * BaseAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $applicantID
 * @property blob $attachment
 * @property Applicant $Applicant
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseAttachment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('attachment');
        $this->hasColumn('applicantID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('attachment', 'blob', null, array(
             'type' => 'blob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Applicant', array(
             'local' => 'applicantID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}