<?php

/**
 * BasePageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $class
 * @property Doctrine_Collection $Page
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BasePageType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('page_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('class', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Page', array(
             'local' => 'id',
             'foreign' => 'pageType'));
    }
}