<?php

/**
 * BaseRecommendation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $recommendationPageID
 * @property integer $answerID
 * @property integer $LORAnswerID
 * @property string $urlKey
 * @property string $email
 * @property boolean $waiveViewRight
 * @property timestamp $invitationSent
 * @property Answer $Answer
 * @property Answer $LORAnswer
 * @property RecommendationPage $RecommendationPage
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseRecommendation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('recommendation');
        $this->hasColumn('recommendationPageID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('answerID', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('LORAnswerID', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             ));
        $this->hasColumn('urlKey', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('waiveViewRight', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('invitationSent', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answerID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Answer as LORAnswer', array(
             'local' => 'LORAnswerID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('RecommendationPage', array(
             'local' => 'recommendationPageID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}