<?php

/**
 * BaseDecision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $applicantID
 * @property timestamp $nominateAdmit
 * @property timestamp $nominateDeny
 * @property timestamp $finalAdmit
 * @property timestamp $finalDeny
 * @property timestamp $offerResponseDeadline
 * @property timestamp $decisionLetterSent
 * @property timestamp $decisionLetterViewed
 * @property timestamp $acceptOffer
 * @property timestamp $declineOffer
 * @property Applicant $Applicant
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseDecision extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('decision');
        $this->hasColumn('applicantID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nominateAdmit', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('nominateDeny', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finalAdmit', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('finalDeny', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('offerResponseDeadline', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('decisionLetterSent', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('decisionLetterViewed', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('acceptOffer', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('declineOffer', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Applicant', array(
             'local' => 'applicantID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}