<?php

/**
 * BaseCitizenship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $answerID
 * @property string $citizenship
 * @property string $birthCity
 * @property string $birthState
 * @property string $birthCountry
 * @property boolean $stateResident
 * @property string $citizenshipCountry
 * @property timestamp $permanentResidentDate
 * @property string $visaType
 * @property Answer $Answer
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseCitizenship extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('citizenship');
        $this->hasColumn('answerID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('citizenship', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('birthCity', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('birthState', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('birthCountry', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('stateResident', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('citizenshipCountry', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('permanentResidentDate', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('visaType', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answerID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}