<?php

/**
 * BaseStatusType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Answer
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseStatusType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('status_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Answer', array(
             'local' => 'id',
             'foreign' => 'publicStatus'));
    }
}