<?php

/**
 * BaseApplicantVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $applicantID
 * @property string $variableName
 * @property blob $value
 * @property Applicant $Applicant
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseApplicantVariable extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('applicant_variable');
        $this->hasColumn('applicantID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('variableName', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             ));


        $this->index('applicant_variable', array(
             'fields' => 
             array(
              0 => 'applicantID',
              1 => 'variableName',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Applicant', array(
             'local' => 'applicantID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}