<?php

/**
 * BasePayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $applicantID
 * @property integer $paymentTypeID
 * @property double $amount
 * @property string $approvalCode
 * @property integer $transactionId
 * @property integer $checkNumber
 * @property string $rechargeAccount
 * @property Applicant $Applicant
 * @property PaymentType $PaymentType
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BasePayment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('payment');
        $this->hasColumn('applicantID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('paymentTypeID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('amount', 'double', null, array(
             'type' => 'double',
             ));
        $this->hasColumn('approvalCode', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('transactionId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('checkNumber', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rechargeAccount', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Applicant', array(
             'local' => 'applicantID',
             'foreign' => 'id',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('PaymentType', array(
             'local' => 'paymentTypeID',
             'foreign' => 'id'));
    }
}