<?php

/**
 * BaseCycle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property timestamp $start
 * @property timestamp $end
 * @property Doctrine_Collection $Application
 * @property Doctrine_Collection $GlobalPage
 * @property Doctrine_Collection $DefaultUsers
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseCycle extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('cycle');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'nospace' => true,
             'length' => '50',
             ));
        $this->hasColumn('start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->check('end > start');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Application', array(
             'local' => 'id',
             'foreign' => 'cycleID'));

        $this->hasMany('GlobalPage', array(
             'local' => 'id',
             'foreign' => 'cycleID'));

        $this->hasMany('User as DefaultUsers', array(
             'local' => 'id',
             'foreign' => 'defaultCycle'));
    }
}