<?php

/**
 * BaseGlobalPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pageID
 * @property integer $cycleID
 * @property Page $Page
 * @property Cycle $Cycle
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseGlobalPage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('global_page');
        $this->hasColumn('pageID', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cycleID', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Page', array(
             'local' => 'pageID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Cycle', array(
             'local' => 'cycleID',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}