<?php

/**
 * BasePaymentType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $class
 * @property Doctrine_Collection $Variables
 * @property Doctrine_Collection $Payment
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BasePaymentType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('payment_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('class', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PaymentTypeVariable as Variables', array(
             'local' => 'id',
             'foreign' => 'paymentTypeID'));

        $this->hasMany('Payment', array(
             'local' => 'id',
             'foreign' => 'paymentTypeID'));
    }
}