<?php

/**
 * BaseAdminVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property blob $value
 * 
 * @package    jazzee
 * @subpackage orm
 */
abstract class BaseAdminVariable extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_variable');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('value', 'blob', null, array(
             'type' => 'blob',
             ));


        $this->index('variable_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}