<?php

/**
 * ApplicantVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author      <>
 */
class ApplicantVariable extends BaseApplicantVariable
{

}