<?php

/**
 * GlobalPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class GlobalPage extends BaseGlobalPage
{

}