<?php

/**
 * GREScore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 * @license http://jazzee.org/license.txt
 */
class GREScore extends BaseGREScore
{

}