<?php

/**
 * JazzeeConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 */
class JazzeeConfig extends BaseJazzeeConfig
{

}