<?php

/**
 * PageType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PageType extends BasePageType
{

}