<?php

/**
 * PaymentTypeVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 */
class PaymentTypeVariable extends BasePaymentTypeVariable
{

}