<?php

/**
 * PaymentVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 */
class PaymentVariable extends BasePaymentVariable
{

}