<?php

/**
 * Recommendation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 * @license http://jazzee.org/license.txt
 */
class Recommendation extends BaseRecommendation{
  
  /**
   * Before a new record is created generate a random urlKey value
   */
  public function preInsert(){
    //The prefix is a random string because uniqid is not random
    $prefix = substr(sha1(mt_rand()),rand(0,20),rand(5,10));
    $this->urlKey = $this->answerID . uniqid($prefix. true);
  }

}