<?php

/**
 * Score
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 */
class Score extends BaseScore{
  public $Score;
  /**
   * Since we can't get to the constructor this is a proxy
   */
  public function construct(){
    $this->loadMatchedScore();
  }
  
  /**
   * Load the matched score after every save
   */
  public function postSave(){
    $this->loadMatchedScore();
  }
  
  /**
   * Try and load the matched score into $Score
   */
  protected function loadMatchedScore(){
    $this->Score = null;
    if($this->scoreID){
      switch($this->scoreType){
        case 'gre':
          $this->Score = Doctrine::getTable('GREScore')->find($this->scoreID);
          break;
        case 'toefl':
          $this->Score = Doctrine::getTable('TOEFLScore')->find($this->scoreID);
          break;
      }
    }
  }
  
  /**
   * Search for any scores that match the registration number
   */
  public function makeMatch(){
    if(empty($this->scoreID)){
      switch($this->scoreType){
        case 'gre':
          $q = Doctrine_Query::create()
            ->select('id')
            ->from('GREScore')
            ->where('RegistrationNumber = ?', $this->registrationNumber)
            ->andWhere('TestMonth = ?', $this->testMonth)
            ->andWhere('TestYear = ?', $this->testYear);
          break;
        case 'toefl':
          $q = Doctrine_Query::create()
            ->select('id')
            ->from('TOEFLScore')
            ->where('RegistrationNumber = ?', $this->registrationNumber)
            ->andWhere('TestMonth = ?', $this->testMonth)
            ->andWhere('TestYear = ?', $this->testYear);
          break;
      }
      $scores = $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
      if(!empty($scores)){
        $this->scoreID = $scores[0]['id'];
      }
    }
  }
}