<?php

/**
 * Score
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jazzee
 * @subpackage orm
 * @author     Jon Johnson <jon.johnson@ucsf.edu>
 */
class Score extends BaseScore{
  public $Score;
  /**
   * Since we can't get to the constructor this is a proxy
   */
  public function construct(){
    $this->loadMatchedScore();
  }
  
  /**
   * Load the matched score after every save
   */
  public function postSave(){
    $this->loadMatchedScore();
  }
  
  /**
   * Try and load the matched score into $Score
   */
  protected function loadMatchedScore(){
    $this->Score = null;
    if($this->scoreID){
      switch($this->scoreType){
        case 'gre':
          $this->Score = Doctrine::getTable('GREScore')->find($this->scoreID);
          break;
        case 'toefl':
          $this->Score = Doctrine::getTable('TOEFLScore')->find($this->scoreID);
          break;
      }
    }
  }
  
  /**
   * Search for any scores that match the registration number
   */
  public function makeMatch(){
    if(empty($this->scoreID)){
      switch($this->scoreType){
        case 'gre':
          $score = Doctrine::getTable('GREScore')->findOneByRegistrationNumber($this->registrationNumber);
          break;
        case 'toefl':
          $score = Doctrine::getTable('TOEFLScore')->findOneByRegistrationNumber($this->registrationNumber);
          break;
      }
      if($score){
        $this->scoreID = $score->id;
      }
    }
  }
}